[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
  "cd backend && npm install && npm run build && npx prisma generate"
]

[start]
cmd = "cd backend && npx prisma migrate deploy && node dist/server.js"
